
//npx playwright  codegen -o  mycodege.spec.ts  
// //generated by above
import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('https://demo.nopcommerce.com/');
  await expect(page.getByRole('textbox', { name: 'Search store' })).toBeVisible();
  await expect(page.getByRole('banner')).toContainText('Log in');
  await page.getByRole('textbox', { name: 'Search store' }).click();
  await page.getByRole('radio', { name: 'Excellent' }).check();
  await page.getByRole('listitem').filter({ hasText: 'Good' }).click();
  await page.getByRole('radio', { name: 'Poor' }).check();
  await page.getByRole('listitem').filter({ hasText: 'Very bad' }).check();
  await page.getByRole('radio', { name: 'Very bad' }).check();
  await page.getByRole('radio', { name: 'Excellent' }).click();
  page.once('dialog', dialog => {
    console.log(`Dialog message: ${dialog.message()}`);
    dialog.dismiss().catch(() => {});
  });
  await page.getByRole('button', { name: 'Vote' }).click();
  await page.getByRole('link', { name: 'View News Archive' }).click();
});